### ISSUE TITLE
Error running in production mode

### ISSUE THREAD

**Issue by tonymcbeth** [rossmartin/ionic2-alpha-scroll#5]
Hi,

When running in the browser with 'ionic serve' everything works as expected. If i run on a device or emulator i get the following error

` Error: Error at
            /[Removed]/.tmp/node_modules/ionic2-alpha-scroll/ion-alpha-scroll.ngfactory.ts:74:7
[16:01:52]  Supplied parameters do not match any signature of call target.
[16:01:52]  ngc failed
[16:01:52]  ionic-app-script task: "build"
[16:01:52]  Error: Error`

I'm running version 1.0.5

Tony

**Comment by rossmartin** [comment]
Thanks for reporting, I'll look into this.  What version of Ionic 2 are you using?  Can you run `ionic info` from the root of your project and let me know what output you get?

Maybe you can try the [example app from here](https://github.com/rossmartin/ionic2-alpha-scroll-example) and see if you still have the build problem?  This problem might be because of an older version of TypeScript or the Ionic CLI.

**Comment by tonymcbeth** [comment]
I'm running the following versions

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.8.6
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.1 Build version 8B62

When running the example project i get the same error, although i had to uncomment the <ion-alpha-scroll tag.

**Comment by rossmartin** [comment]
Thanks.  I'm looking into this, I wish `ngc` gave more help when it fails!

**Comment by rossmartin** [comment]
This issue is fixed in [1.0.6](https://github.com/rossmartin/ionic2-alpha-scroll/tree/1.0.6),  thanks for reporting.
